apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: reta-database
        - name: POSTGRES_USER
          value: reta
        - name: POSTGRES_PASSWORD
          value: ReTa@2024!
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: duogglong/reta-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
      - name: auth-pod
        image: duogglong/reta-auth:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8890
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-pod
  template:
    metadata:
      labels:
        app: customer-pod
    spec:
      containers:
      - name: customer-pod
        image: duogglong/reta-customer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8889

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-pod
  template:
    metadata:
      labels:
        app: common-pod
    spec:
      containers:
      - name: common-pod
        image: duogglong/reta-common:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8891

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-pod
  template:
    metadata:
      labels:
        app: recruitment-pod
    spec:
      containers:
      - name: recruitment-pod
        image: duogglong/reta-recruitment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8892