apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: reta-fe-pod
    service: fe-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: reta-fe-pod